name: Run RPA CRAWL Script Daily

on:
  schedule:
    - cron: '30 18 * * *'  # 01:30 Việt Nam
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start)'
        required: true
        default: 'start'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - name: Run script
        env:
          CI: true
          MAX_POSTS: 2000
        run: python rpa_crawl_update.py